<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\TriLink.Plugin.Abstractions\TriLink.Plugin.Abstractions.csproj" />
    <ProjectReference Include="..\..\TriLink.PluginHost\TriLink.PluginHost.csproj" />
  </ItemGroup>
</Project>
